queues:
  - name: q_in
    capacity: 256
  - name: q_out
    capacity: 256

stages:
  - type: nats_jetstream_source
    name: source
    threads: 1
    output_queue: q_in
    config:
      subject: flow.jobs
      stream_name: FLOW
      durable_name: FLOW_PIPE
      poll_timeout_ms: 1000

  - type: rpc_transform_stage
    name: transform
    threads: 2
    input_queue: q_in
    output_queue: q_out
    config:
      processing_delay_ms: 1000

  - type: nats_jetstream_sink
    name: sink
    threads: 1
    input_queue: q_out
    config:
      url: nats://127.0.0.1:4222
      subject: flow.replies
